name: tarball

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout Chromium
        run: ./checkout.py

      - name: Create source tarball
        run: |
          ./export_tarball.py chromium --progress
          ls -lh *.tar.xz

      - name: Create sha256sum
        run: sha256sum *.tar.xz > .tar.xz.sha256

      - name: Upload Binary Files
        uses: actions/upload-artifact@v3
        with:
          path: |
            *.tar.xz
            .tar.xz.sha256
          retention-days: 1


  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: python -m pip install feedparser

      - name: Download Files
        uses: actions/download-artifact@v3

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Chromium ${{ github.ref_name }}
          artifacts: artifact/*.tar.xz
          artifactErrorsFailBuild: true
