name: tarball

on: [push, pull_request]

env:
  VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '121.0.6147.0' }}

jobs:
  build:
    runs-on: ubuntu-22.04
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        targetOs: [linux, mac, win]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout Chromium
        run: ./checkout.py --target-os ${{ matrix.targetOs }} --revision $VERSION

      - name: Create source tarball
        run: |
          ./export_tarball.py chromium-$VERSION-${{ matrix.targetOs }} --version $VERSION --src-dir src --progress
          ls -lh *.tar.xz

      - name: Upload Binary Files
        uses: actions/upload-artifact@v3
        with:
          path: '*.tar.xz'
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Files
        uses: actions/download-artifact@v3

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Chromium ${{ github.ref_name }}
          body: ''
          draft: true
          artifacts: artifact/*.tar.xz
          artifactErrorsFailBuild: true
