name: tarball

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout Chromium
        run: ./checkout.py --revision 121.0.6147.0

      - name: Create source tarball
        run: |
          ./export_tarball.py test --version 121.0.6147.0 --src-dir src --progress
          ls -l test.tar.gz
